language: go
go:
  - 1.4
  - tip

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - git submodule update --init --recursive
  - cd tgl/lib/tgl && ./configure && make

install:
  - go build -x -v

script:
  - go test -v
  - go test -i -race ./...
  - go test -v -race ./...

notifications:
  email:
    recipients:
      - gloob@litio.org
    on_success: change
    on_failure: always
