language: go
go:
  - 1.4
  - tip

branches:
  only:
    - master

before_install:
  - cd tgl/lib/tgl && ./configure && make
  - cd ../../

install:
  - go build -x -v

script:
  - go test -v
  - go test -i -race ./...
  - go test -v -race ./...

notifications:
  email:
    recipients:
      - gloob@litio.org
    on_success: change
    on_failure: always
